apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: app1-rule
  namespace: default
spec:
  rules:
    - host: ec2-18-197-63-218.eu-central-1.compute.amazonaws.com
      http:
        paths:
          - backend:
              serviceName: app1-nginx
              servicePort: 8888
            path: /app1
  # This section is only required if TLS is to be enabled for the Ingress
  #     tls:
  #             - hosts:
  #                         - www.example.com
  #                                   secretName: example-tls
  #
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: app2-rule
  namespace: default
spec:
  rules:
    - host: ec2-18-197-63-218.eu-central-1.compute.amazonaws.com
      http:
        paths:
          - backend:
              serviceName: app2-nginx
              servicePort: 8888
            path: /app2
  # This section is only required if TLS is to be enabled for the Ingress
  #     tls:
  #             - hosts:
  #                         - www.example.com
  #                                   secretName: example-tls
  #

