---
# tasks file for yum-install-latest-stable-docker
- name: Yum Install Docker
  yum:
    name: docker-ce
    state: latest
- name:  Start Docker Engine
  systemd:
    state: started
    name: docker
- name:  Adding Ec2-user To Docker 
  user:
   name: boaz
   shell: /bin/bash
   groups: dockerroot
   append: yes
- name:  Check Docker Runnig
  shell: docker info
