---
- hosts: all
  tasks:
    - name: Yum Remove Docker
      yum:
        name: docker
        state: removed 
    - name: Check Docker Not Runnig
      shell: docker info
      ignore_errors: yes
    - name: Stop Minikube
      shell: minikube stop
      ignore_errors: yes
    - name: Minikube Delete   
      shell: minikube delete
      ignore_errors: yes
    - name: Delete minikube binary
      file:
        state: absent
        path: "/bin/minikube"
      ignore_errors: yes 
    - name: Check Minikube Deleted
      shell: minikube status
      ignore_errors: yes
    - name: Delete kubectl       
      file:
        state: absent
        path: "/bin/kubectl"
      ignore_errors: yes
